 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: containerwebappdemo
 spec:
   replicas: 5
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: containerwebappdemo
           image: ordinadockerworkshopms/containerwebappdemo:latest
           ports:
             - containerPort: 80