version: '3.4'

services:
  containerwebappdemo:
    image: ${DOCKER_REGISTRY-ordinadockerworkshopms}/containerwebappdemo
    build:
      context: .
      dockerfile: ContainerWebAppDemo/Dockerfile

  imageservice:
    image: ${DOCKER_REGISTRY-ordinadockerworkshopms}/imageservice
    build:
      context: .
      dockerfile: ImageService/Dockerfile


  messageservice:
    image: ${DOCKER_REGISTRY-ordinadockerworkshopms}/messageservice
    build:
      context: .
      dockerfile: MessageService/Dockerfile

