 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: messageservice
 spec:
   replicas: 5
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: messageservice
           image: ordinadockerworkshopms/messageservice:latest
           ports:
             - containerPort: 80